#!/bin/bash

FORBIDDEN_BRANCHES="master main dev development"
BRANCH=$(git rev-parse --abbrev-ref HEAD)

BOLD=$(tput bold)
YELLOW=$(tput setaf 3)
CYAN=$(tput setaf 6)
RESET=$(tput sgr0)

for forbidden in $FORBIDDEN_BRANCHES; do
    if [ "$forbidden" == "$BRANCH" ]; then
        echo
        echo "${BOLD}You are currently in branch ${YELLOW}$BRANCH${RESET}."
        echo "    Are you sure you want to commit to this branch?"
        echo
	echo "(Use the -n flag to bypass this message.)"
        exit 1
    fi
done
